const mongoose = require('mongoose');

const investmentInvoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      required: false, // Generated by pre-save hook
      unique: true,
    },
    orderId: {
      type: String,
      required: true,
      unique: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    customerName: {
      type: String,
      required: true,
    },
    customerEmail: {
      type: String,
    },
    customerPhone: {
      type: String,
    },
    // Transaction Details
    orderType: {
      type: String,
      enum: ['buy', 'sell'],
      required: true,
    },
    transactionType: {
      type: String,
      enum: ['GOLD', 'SILVER'],
      required: true,
    },
    product: {
      type: String, // e.g., "GOLD24"
      required: true,
    },
    // Quantity & Pricing
    quantity: {
      type: Number, // in grams
      required: true,
    },
    ratePerGram: {
      type: Number,
      required: true,
    },
    amount: {
      type: Number, // Base amount (without GST)
      required: true,
    },
    // GST Details
    gstRate: {
      type: Number,
      default: 3, // 3%
    },
    gstAmount: {
      type: Number,
      default: 0,
    },
    // Discount (if any)
    discountCode: {
      type: String,
      default: null,
    },
    discount: {
      type: Number,
      default: 0,
    },
    // Final Amount
    totalInvoiceValue: {
      type: Number,
      required: true,
    },
    // Payment Details
    paymentMethod: {
      type: String,
      default: 'UPI',
    },
    transactionId: {
      type: String,
    },
    // Invoice Status
    status: {
      type: String,
      enum: ['draft', 'issued', 'paid', 'cancelled'],
      default: 'issued',
    },
    // Company Details (for invoice header)
    company: {
      name: {
        type: String,
        default: 'Moi Technology Private Limited',
      },
      address: {
        type: String,
        default: '85D, Subbiahpuram main, 3rd street, Thoothukkudi, Tamilnadu - 628003',
      },
      gstin: {
        type: String,
        default: '33AAPCM8850L1ZT',
      },
      pan: {
        type: String,
        default: 'AAPCM8850L',
      },
      cin: {
        type: String,
        default: 'U74999TN2022PTC153068',
      },
      email: {
        type: String,
        default: 'support@auragold.in',
      },
    },
    // Declaration
    declaration: {
      type: [String],
      default: [
        'We declare that the above quantity of goods are kept by the seller in a secure vault and the same is insured by the seller. The seller shall be liable to pay the customer the value of the goods in case of any loss or damage to the goods.',
        'It can be delivered in a form of a minted coin upon request as per the Terms and Conditions.',
      ],
    },
    // Invoice Generation Date
    invoiceDate: {
      type: Date,
      default: Date.now,
    },
    // Metadata
    createdBy: {
      type: String,
      default: 'System',
    },
    updatedBy: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);

// Generate invoice number before saving
investmentInvoiceSchema.pre('save', async function (next) {
  if (this.isNew && !this.invoiceNumber) {
    // Generate invoice number in format: INV-YYYYMMDD-XXXX
    const date = new Date();
    const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
    
    // Find the last invoice of today
    const lastInvoice = await mongoose.model('InvestmentInvoice')
      .findOne({ invoiceNumber: new RegExp(`^INV-${dateStr}`) })
      .sort({ invoiceNumber: -1 });
    
    let sequence = 1;
    if (lastInvoice) {
      const lastSequence = parseInt(lastInvoice.invoiceNumber.split('-').pop());
      sequence = lastSequence + 1;
    }
    
    this.invoiceNumber = `INV-${dateStr}-${String(sequence).padStart(4, '0')}`;
  }
  next();
});

// Index for faster queries
investmentInvoiceSchema.index({ orderId: 1 });
investmentInvoiceSchema.index({ userId: 1 });
investmentInvoiceSchema.index({ invoiceNumber: 1 });
investmentInvoiceSchema.index({ invoiceDate: -1 });
investmentInvoiceSchema.index({ status: 1 });

module.exports = mongoose.model('InvestmentInvoice', investmentInvoiceSchema);

